apiVersion: apps/v1
kind: Deployment
metadata:
  name: "film-application"
  namespace: {{.Values.namespace}}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: "film-application"
  template:
    metadata:
      labels:
        app: "film-application"
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          ports:
            - containerPort: 8080
          env:
            - name: DB_HOST
              valueFrom:
                secretKeyRef:
                  name: app-db-conf
                  key: POSTGRES_HOST
            - name: DB_USER
              valueFrom:
                secretKeyRef:
                  name: app-db-conf
                  key: POSTGRES_USER
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: app-db-conf
                  key: POSTGRES_PASSWORD
            - name: DB_DATABASE
              valueFrom:
                secretKeyRef:
                  name: app-db-conf
                  key: POSTGRES_DB
            command: ["/bin/sh"]
            args:
              - "/bin/sh"
              - "-c"
              - "DB_HOST=$(echo $DB_HOST | base64 -d)"
              - "DB_USER=$(echo $DB_USER | base64 -d)"
              - "DB_PASSWORD=$(echo $DB_PASSWORD | base64 -d)"
              - "DB_DATABASE=$(echo $DB_DATABASE | base64 -d)"