dbName: "bW92aWVzREI="  # Base64-encoded value: "moviesDB"
dbUser: "YWRtaW4="    # Base64-encoded value: "admin"
dbPassword: "c3FsQWRtaW4="  # Base64-encoded value: "sqlAdmin"
replicaCount: 2
image: "h3xbar/final-proj:psgrsql"
imagePullPolicy: Always
resources:
  requests:
    memory: "256Mi"
    cpu: "100m"

persistence:
  size: 4Gi
