# Default values for film-library-app.
namespace: dev

replicaCount: 1  # Replace '3' with the desired number of replicas

image:
  repository: itsvictorfy/final-proj

  tag: 79763f8

  pullPolicy: IfNotPresent
  
service:
  type: LoadBalancer
  port: 8080

database:
  host: postgresdb.database.svc.cluster.local
  database: moviesdb
  user: postgres
  password: sqlAdmin
