apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: db-data-{{ .Release.Name }}
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.persistence.size }}
