apiVersion: v1
kind: Secret
metadata:
  name: db-secret-credentials
  labels:
    app: {{ .Release.Name }}
data:
  POSTGRES_DB: {{ .Values.dbName }}
  POSTGRES_USER: {{ .Values.dbUser }}
  POSTGRES_PASSWORD: {{ .Values.dbPassword }}
