# Default values for film-library-app.
namespace: prod

replicaCount: 2  # Replace '3' with the desired number of replicas

image:
  repository: itsvictorfy/final-proj

  tag: b0ec068

  pullPolicy: IfNotPresent
  
service:
  type: LoadBalancer
  port: 8080

database:
  host: postgresdb.database.svc.cluster.local
  database: moviesdb
  user: postgres
  password: sqlAdmin
